# Generated by Django 6.0.2 on 2026-02-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_name.department')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app_name.project')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='app_name.employee'),
        ),
    ]
